---
- name: Crea contenedor para laboratorios clase02
  hosts: fisicos
  tasks:
    - name: Apaga todos los contenedores
      command: "lxc-stop -n {{ item }}"
      with_items:
        - php
        - hhvm
        - python
        - perl
        - dnsmasq
        - lab-apache
      become: yes
      ignore_errors: true
    - name: Destruye todos los contenedores
      command: "lxc-destroy -n {{ item }}"
      with_items:
        - php
        - hhvm
        - python
        - perl
        - dnsmasq
        - lab-apache
      become: yes
      ignore_errors: true
    - name: Crea contenedor php
      lxc_container:
        name: php
        container_log: true
        container_config:
          - lxc.network.link = br0
          - lxc.start.auto = 1
          - lxc.start.delay = 120
          - lxc.start.order = 0
          - lxc.network.hwaddr = {{ macphp }}
        template: download
        state: started
        template_options: -d ubuntu -r xenial -a amd64
      become: yes
    - name: Crea contenedor hhvm
      lxc_container:
        name: hhvm
        container_log: true
        container_config:
          - lxc.network.link = br0
          - lxc.start.auto = 1
          - lxc.start.delay = 120
          - lxc.start.order = 0
          - lxc.network.hwaddr = {{ machhvm }}
        template: download
        state: started
        template_options: -d ubuntu -r xenial -a amd64
      become: yes
    - name: Crea contenedor python
      lxc_container:
        name: python
        container_log: true
        container_config:
          - lxc.network.link = br0
          - lxc.start.auto = 1
          - lxc.start.delay = 120
          - lxc.start.order = 0
          - lxc.network.hwaddr = {{ macpython }}
        template: download
        state: started
        template_options: -d ubuntu -r xenial -a amd64
      become: yes
    - name: Crea contenedor perl
      lxc_container:
        name: perl
        container_log: true
        container_config:
          - lxc.network.link = br0
          - lxc.start.auto = 1
          - lxc.start.delay = 120
          - lxc.start.order = 0
          - lxc.network.hwaddr = {{ macperl }}
        template: download
        state: started
        template_options: -d ubuntu -r xenial -a amd64
      become: yes
    - name: Crea contenedor dnsmasq
      lxc_container:
        name: dnsmasq
        container_log: true
        container_config:
          - lxc.network.link = br0
          - lxc.start.auto = 1
          - lxc.start.delay = 120
          - lxc.start.order = 0
          - lxc.network.hwaddr = {{ macdnsmasq }}
        template: download
        state: started
        template_options: -d ubuntu -r xenial -a amd64
      become: yes
    - name: Crea contenedor lab-apache
      lxc_container:
        name: lab-apache
        container_log: true
        container_config:
          - lxc.network.link = br0
          - lxc.start.auto = 1
          - lxc.start.delay = 120
          - lxc.start.order = 0
          - lxc.network.hwaddr = {{ maclabapache }}
        template: download
        state: started
        template_options: -d ubuntu -r xenial -a amd64
      become: yes
    - name: Pausa para esperar que levante contenedor
      pause:
        seconds: 30
    - name: Crea configuración base para todos los contenedores
      command: lxc-attach -n {{ item[0] }} -- {{ item[1] }}
      with_nested:
        - [ 'php', 'hhvm', 'python', 'perl', 'dnsmasq', 'lab-apache' ]
        - [ 'apt-get update', 'apt-get dist-upgrade -y', 'apt-get install python ssh sudo psmisc -y', 'systemctl enable ssh', 'systemctl start ssh', 'useradd -s /bin/bash -G sudo -m -p "$6$dF3C39/G$6oRDu6OCq9Td2hU1iN4lRyMTIPtTkq3bIivTAEqxUGOH6LRAkmkGcqjlLN4jT6S1buHEUmCJAqIhqnPcMKbxE1" greencore' ]
      become: yes
