---
- name: Instala laboratorio para clases de nagios
  hosts: fisicos
  tasks:
    - name: Plantilla de jinja para archivo interfaces
      template:
        src: files/interfaces.j2
        dest: /etc/network/interfaces
        mode: 0644
        owner: root
        group: root
      become: yes
    - name: Define un hostname para equipo fisico
      hostname:
        name: "{{ hostname }}"
      become: yes
    - name: Configura kernel para que funcione como router
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes
      become: yes
    - name: Instala paquete de LXC
      apt: 
        name: "{{ item }}"
        state: installed
      with_items:
        - lxc
        - lxc-dev
        - python-pip
        - libguestfs-tools
      become: yes
    - name: Instala dependencias de python para módulo de ansible de LXC
      pip: name=lxc-python2 state=present
      become: yes
    - name: Configura defaults de LXC
      lineinfile:
        regexp: "^lxc.network.link = lxcbr0"
        dest: "/etc/lxc/default.conf"
        line: "lxc.network.link = br0"
        state: present
        backrefs: yes
      become: yes
    - name: Crea directorio para cliente de SSH
      file:
        path: "{{ ansible_env.HOME }}/.ssh/"
        state: directory
        mode: 0755
        owner: greencore
        group: greencore
    - name: Configura cliente de SSH
      copy:
        dest: "{{ ansible_env.HOME }}/.ssh/config"
        content: |
                Host 10.42.25.*
                  StrictHostKeyChecking no
                  UserKnownHostsFile=/dev/null
        owner: greencore
        group: greencore
    - name: Crea reglas de ACL para trabajar en directorio de virtuales
      acl:
        path: /var/lib/libvirt/images/
        entity: greencore
        etype: user
        permissions: rwX
        state: present
        recursive: yes
      become: yes

